"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const containerController_1 = require("../controllers/containerController");
const containersRoutes = (0, express_1.Router)();
containersRoutes.get("/", containerController_1.containerController.getAll);
containersRoutes.get("/:id", containerController_1.containerController.getById);
containersRoutes.get("/:id/parcels", containerController_1.containerController.getParcelsByContainerId);
containersRoutes.post("/toPort", containerController_1.containerController.toPort);
containersRoutes.post("/toWarehouse", containerController_1.containerController.toWarehouse);
exports.default = containersRoutes;
